import { Link } from 'react-router-dom';
import WebsiteLayout, { SectionCTA, InternalLinks } from './WebsiteLayout';

export default function GoogleAdsOptimizationPage({ onOpenApp }: { onOpenApp: () => void }) {
  return (
    <WebsiteLayout
      onOpenApp={onOpenApp}
      title="Google Ads Optimization & PPC Audit Tool — Keyword Lists & Account Auditing | SEAUTO"
      description="Generate expert-level Google Ads keyword lists (broad, phrase, exact match) with negative keywords. Audit ad accounts across Google, Meta, LinkedIn, and Reddit for wasted spend and optimization opportunities."
    >
      <section className="pt-16 pb-20 lg:pt-24 lg:pb-28 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-[#FFF0F5] via-white to-[#F0F7FF]" />
        <div className="absolute top-20 right-20 w-[500px] h-[500px] bg-rose-200/20 rounded-full blur-3xl" />
        <div className="relative max-w-7xl mx-auto px-6">
          <div className="max-w-3xl">
            <span className="inline-block px-3 py-1 rounded-full bg-rose-100 text-rose-700 text-xs font-bold uppercase tracking-wider mb-6">Advertising Intelligence</span>
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight leading-[1.1] mb-6">
              Smarter Ads. <span className="bg-gradient-to-r from-rose-500 to-pink-500 bg-clip-text text-transparent">Less Wasted Spend.</span>
            </h1>
            <p className="text-xl text-[#6E6E73] leading-relaxed mb-8">
              SEAUTO generates conversion-optimized keyword lists from your organic ranking data and AI analysis, then audits your ad accounts across platforms to eliminate waste and maximize ROAS.
            </p>
            <button onClick={onOpenApp} className="px-8 py-3.5 rounded-full bg-[#0071E3] text-white font-semibold hover:bg-[#0077ED] transition-all shadow-lg cursor-pointer">
              Generate Keywords Free
            </button>
          </div>
        </div>
      </section>

      {/* Keyword Generation */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-6">
          <h2 className="text-3xl lg:text-4xl font-bold text-center mb-4">AI Keyword List Generation</h2>
          <p className="text-lg text-[#6E6E73] text-center max-w-2xl mx-auto mb-14">SEAUTO analyzes your top-performing organic keywords and uses AI to generate comprehensive keyword lists for Google Ads campaigns.</p>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {[
              { title: 'Broad Match Keywords', desc: 'Cast a wide net with AI-suggested broad match terms. Includes your existing ranking keywords plus new opportunities most likely to drive conversions.', color: 'from-blue-500 to-cyan-500' },
              { title: 'Phrase Match Keywords', desc: 'More targeted than broad match. AI identifies the exact phrases your potential customers search for, based on your site\'s content and conversion patterns.', color: 'from-violet-500 to-purple-500' },
              { title: 'Exact Match Keywords', desc: 'Precision targeting for maximum ROAS. SEAUTO identifies the highest-converting exact match terms from your organic data and AI analysis of user intent.', color: 'from-emerald-500 to-teal-500' },
              { title: 'Negative Keywords', desc: 'An expansive negative keyword list generated by AI to prevent wasted ad spend. Covers irrelevant queries, informational searches, and competitor terms you shouldn\'t bid on.', color: 'from-rose-500 to-red-500' },
            ].map((type) => (
              <div key={type.title} className="bg-white rounded-2xl p-7 border border-gray-100 hover:shadow-lg transition-all">
                <div className={`w-10 h-10 rounded-xl bg-gradient-to-br ${type.color} flex items-center justify-center mb-4`}>
                  <svg className="w-5 h-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z" /></svg>
                </div>
                <h3 className="text-lg font-bold mb-3">{type.title}</h3>
                <p className="text-sm text-[#6E6E73] leading-relaxed">{type.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Multi-Platform Auditing */}
      <section className="py-20 bg-[#FAFAFA]">
        <div className="max-w-7xl mx-auto px-6">
          <h2 className="text-3xl font-bold text-center mb-4">Multi-Platform Ad Account Auditing</h2>
          <p className="text-lg text-[#6E6E73] text-center max-w-3xl mx-auto mb-14">
            Upload your ad account data and get AI-powered audits covering performance, budget efficiency, creative quality, and account structure.
          </p>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {[
              { title: 'Google Ads', desc: 'Wasted spend analysis, Quality Score breakdowns, bid strategy optimization, ad extension gaps, keyword cannibalization detection, and search term mining.' },
              { title: 'Meta Ads', desc: 'Creative fatigue detection, audience overlap analysis, frequency cap optimization, retargeting window tuning, and competitor creative benchmarking.' },
              { title: 'LinkedIn Ads', desc: 'B2B campaign benchmarking, audience quality scoring, lead gen form friction analysis, and budget efficiency relative to LinkedIn-specific CPCs.' },
              { title: 'Reddit Ads', desc: 'Community targeting analysis, subreddit performance comparison, creative fit scoring, and bid inefficiency identification for Reddit\'s unique ad platform.' },
              { title: 'Budget & Spend', desc: 'Cross-channel budget optimization, wasted spend aggregation, channel mix rebalancing recommendations, and ROAS forecasting by platform.' },
              { title: 'Attribution & Tracking', desc: 'Attribution model comparison (last-click vs multi-touch), conversion path analysis, UTM consistency review, and cross-channel tracking validation.' },
            ].map((platform) => (
              <div key={platform.title} className="bg-white rounded-2xl p-6 border border-gray-100 hover:shadow-lg transition-all">
                <h3 className="font-bold mb-2">{platform.title}</h3>
                <p className="text-sm text-[#6E6E73] leading-relaxed">{platform.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Organic + Paid synergy */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-6">
          <h2 className="text-3xl font-bold text-center mb-4">Organic + Paid: Better Together</h2>
          <p className="text-lg text-[#6E6E73] text-center max-w-3xl mx-auto mb-14">
            SEAUTO is the only platform that combines <Link to="/features/keyword-rank-tracker" className="text-[#0071E3] hover:underline">organic keyword tracking</Link> with advertising intelligence. Your organic ranking data directly informs your paid keyword strategy.
          </p>
          <div className="grid md:grid-cols-3 gap-6 max-w-4xl mx-auto text-center">
            {[
              { title: 'Organic Data Informs Paid', desc: 'Keywords you rank for organically become your highest-confidence paid targets — you already know they\'re relevant to your business.' },
              { title: 'Gap Analysis', desc: 'Keywords you don\'t rank for organically but should? Target them with paid ads while your SEO catches up.' },
              { title: 'Unified Strategy', desc: 'Stop treating organic and paid as separate channels. SEAUTO gives you one view of your entire search presence.' },
            ].map((c) => (
              <div key={c.title} className="p-6">
                <h3 className="font-bold mb-2">{c.title}</h3>
                <p className="text-sm text-[#6E6E73] leading-relaxed">{c.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <SectionCTA onOpenApp={onOpenApp} />

      <InternalLinks links={[
        { to: '/features/keyword-rank-tracker', label: 'Keyword Rank Tracker', desc: 'Organic keyword data that powers your advertising strategy.' },
        { to: '/features/seo-audit-tool', label: 'SEO Audit Tool', desc: 'Optimize your landing pages for better Quality Scores and conversions.' },
        { to: '/features/ai-website-builder', label: 'AI Website Builder', desc: 'Build high-converting landing pages for your ad campaigns.' },
        { to: '/solutions/seo-agency-software', label: 'For SEO Agencies', desc: 'Offer PPC management alongside SEO for your agency clients.' },
        { to: '/pricing', label: 'View Pricing', desc: 'Advertising features are included in the Plus plan and above.' },
        { to: '/resources/automated-seo', label: 'Automated SEO Guide', desc: 'How organic and paid search work together in an automated strategy.' },
      ]} />
    </WebsiteLayout>
  );
}
